<?php

namespace App\Enums;

enum ApplicationStatus: string
{
    case SUBMITTED = 'SUBMITTED';
    case APPROVED_DEPT_HEAD = 'APPROVED_DEPT_HEAD';
    case REJECTED_DEPT_HEAD = 'REJECTED_DEPT_HEAD';
    case APPROVED_ASSO_DEAN = 'APPROVED_ASSO_DEAN';
    case REJECTED_ASSO_DEAN = 'REJECTED_ASSO_DEAN';
    case APPROVED_DEAN = 'APPROVED_DEAN';
    case REJECTED_DEAN = 'REJECTED_DEAN';
    case APPROVED_NISIT_DEV = 'APPROVED_NISIT_DEV';
    case REJECTED_NISIT_DEV = 'REJECTED_NISIT_DEV';
    case APPROVED_BOARD = 'APPROVED_BOARD';
    case REJECTED_BOARD = 'REJECTED_BOARD';
}
