name: Laravel CI/CD to Local K8S

on:
  push:
    branches:
      [ "main" ,"feature/setup-cicd"]

jobs:
  # JOB 1: ทดสอบโค้ด (รันบน Cloud ของ GitHub เพื่อความเร็ว)
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=20s
          --health-timeout=10s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, dom, curl, libxml, mysql
      - name: Install Dependencies
        run: |
          php -r "copy('.env.example', '.env');"
          composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          php artisan key:generate

      - name: Install NPM dependencies & Build Assets
        run: |
          npm install
          npm run build

      - name: Run Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: password
        run: php artisan test

  # JOB 2: Build Docker Image (ถ้าจะใช้ K8S ต้องมีขั้นตอนนี้เพื่อให้ K8S ดึงภาพไปรันได้)
  build-docker:
    needs: laravel-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/laravel-app:latest

  # JOB 3: สั่ง K8S ในเครื่อง Local (รันบน Self-hosted Runner)
  deploy-local:
    needs: build-docker
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to K8S
        run: |
          mkdir -p ~/.kube

          # 🌟 เพิ่มบรรทัดนี้: ให้ GitHub Actions ดึง Secret มาสร้างใน K8s ทันที
          kubectl create secret generic laravel-secrets \
            --from-literal=APP_KEY="${{ secrets.LARAVEL_APP_KEY }}" \
            --from-literal=DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            --dry-run=client -o yaml | kubectl apply -f -
          sleep 5
          # หลังจากสร้าง Secret เสร็จ ก็สั่ง Deploy ตัวแอปต่อได้เลย
          kubectl apply -f k8s/laravel-deploy.yml
#          kubectl rollout restart deployment/laravel-app
          kubectl patch deployment laravel-app \
          -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"build_time\":\"$(date +%s)\"}}}}}"
